### ISSUE TITLE
Prompt for textbook generation

### ISSUE THREAD

**Issue by UniverseFly** [SciPhi-AI/synthesizer#137]
Hi, thanks for the great project. I may have missed something but are there any pointers to the textbook generation prompt?

**Comment by emrgnt-cmplxty** [comment]
Hi,

There was an entire workflow on an old commit that I slowly retired due to lack of interest.

If you are interested, [you run check the repository from this hash](https://github.com/SciPhi-AI/synthesizer/tree/5f918b7f32099a68066e041a42968c73e6a3f542/sciphi/synthetic_data/textbook_generation).

If you have need to generate a lot of synthetic data I could re-introduce this functionality.

**Comment by UniverseFly** [comment]
Thank you @emrgnt-cmplxty. I was just interested in the overall idea, and the commit you shared helps a lot!

**Comment by emrgnt-cmplxty** [comment]
please let me know how it goes - happy to chat about it over a quick call.
